language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

branches:
  only:
    - master

before_script:
  - git config --global user.email "tardieu.f@hotmail.fr"
  - git config --global user.name "ftardieu"
  - git remote set-url origin https://${github_token}@github.com/ftardieu/riotAPI.git

script:
  - npm test
  - npm run build

after_success:
  - git fetch origin dev:dev master:master --tags
  - standard-version
  - git checkout dev
  - git merge --ff
  - git push origin --tags

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
