language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

branches:
  only:
    - master

after_success:
  - git fetch origin dev:dev master:master --tags
  - standard-version
  - git checkout dev
  - git checkout -f
  - git push origin --tags

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
